/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.13/userguide/multi_project_builds.html in the Gradle documentation.
 */

dependencyResolutionManagement {
    @Suppress("UnstableApiUsage")
    repositories {
        mavenLocal()
        // Optional private repository (enabled when credentials exist)
        val aliyunUser = providers.gradleProperty("aliyun.maven.username").orNull
        val aliyunPass = providers.gradleProperty("aliyun.maven.password").orNull
        if (!aliyunUser.isNullOrBlank() && !aliyunPass.isNullOrBlank()) {
            maven {
                credentials {
                    username = aliyunUser
                    password = aliyunPass
                }
                url = uri("https://packages.aliyun.com/67053c6149e9309ce56b9e9e/maven/code-gen")
            }
        }
        maven {
            url = uri("https://maven.aliyun.com/repository/public")
        }
        mavenCentral()
    }
}

rootProject.name = "codegen-plugin"
include("plugin")
include("ksp-processor")
