/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/8.13/userguide/custom_plugins.html in the Gradle documentation.
 */

plugins {
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    `java-gradle-plugin`

    // Apply the Kotlin JVM plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    `maven-publish`
}

group = "com.only4"
version = "0.1.5-SNAPSHOT"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Gradle plugin API
    implementation(gradleApi())
    implementation(gradleKotlinDsl())

    // KSP processor module (for metadata models)
    implementation(project(":ksp-processor"))

    // Database dependencies
    implementation("mysql:mysql-connector-java:8.0.33")
    implementation("org.postgresql:postgresql:42.7.2")

    // JSON processing
    implementation("com.alibaba:fastjson:2.0.43")
    implementation("com.google.code.gson:gson:2.10.1")

    implementation("io.pebbletemplates:pebble:3.2.4")

    // Kotlin reflection
    implementation(kotlin("reflect"))

    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

gradlePlugin {
    website.set("https://github.com/yourorg/codegen-plugin")
    vcsUrl.set("https://github.com/yourorg/codegen-plugin")

    // Define the plugin
    val codegen by plugins.creating {
        id = "com.only4.codegen"
        implementationClass = "com.only4.codegen.CodegenPlugin"
        displayName = "Codegen Plugin"
        description = "Generates code from database schema using templates"
    }
}

tasks.named<Test>("test") {
    // Use JUnit Jupiter for unit tests.
    useJUnitPlatform()
}

// 添加源码 jar 任务
val sourcesJar by tasks.registering(Jar::class) {
    archiveClassifier.set("sources")
    from(sourceSets.main.get().allSource)
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
            artifact(sourcesJar)
            groupId = project.group.toString()
            artifactId = project.name
            version = project.version.toString()
        }
    }
    repositories {
        maven {
            name = "AliYunMaven"
            url = uri("https://packages.aliyun.com/67053c6149e9309ce56b9e9e/maven/code-gen")
            credentials {
                username = providers.gradleProperty("aliyun.maven.username").get()
                password = providers.gradleProperty("aliyun.maven.password").get()
            }
        }
    }
}
