package com.only4.codegen.engine.generation.design

import com.only4.codegen.engine.generation.IGenerationStrategy
import com.only4.codegen.engine.output.GenerationResult
import com.only4.codegen.engine.output.OutputType
import com.only4.codegen.misc.concatPackage

class V2ClientHandlerStrategy : IGenerationStrategy<DesignV2Context> {
    override fun generate(context: DesignV2Context): List<GenerationResult> {
        val pkg = concatPackage(context.basePackage, "adapter", context.packageName)
        val fileName = "${context.className}.kt"

        val content = buildString {
            appendLine("package $pkg")
            appendLine()
            appendLine("/**")
            appendLine(" * ${context.description}")
            appendLine(" * Generated by V2 engine")
            appendLine(" */")
            appendLine("class ${context.className} {")
            appendLine("    fun handle() { /* TODO */ }")
            appendLine("}")
        }

        return listOf(
            GenerationResult(
                fileName = fileName,
                content = content,
                packageName = pkg,
                type = OutputType.SERVICE,
            )
        )
    }
}

