package com.only4.codegen.engine.generation.design

import com.only4.codegen.engine.generation.IGenerationStrategy
import com.only4.codegen.engine.output.GenerationResult
import com.only4.codegen.engine.output.OutputType

class V2CommandStrategy : IGenerationStrategy<DesignV2Context> {
    override fun generate(context: DesignV2Context): List<GenerationResult> {
        val fileName = "${context.className}.kt"

        val content = buildString {
            appendLine("package ${context.finalPackage}")
            appendLine("import com.only4.cap4k.ddd.core.application.RequestParam")
            appendLine("import com.only4.cap4k.ddd.core.application.command.Command")
            appendLine("import com.only4.cap4k.ddd.core.share.Mediator")
            appendLine()
            appendLine("/**")
            appendLine(" * ${context.description}")
            appendLine(" * Generated by V2 engine")
            appendLine(" */")
            appendLine("object ${context.className} {")
            appendLine("    @org.springframework.stereotype.Service")
            appendLine("    class Handler : Command<Request, Response> {")
            appendLine("        override fun exec(request: Request): Response {")
            appendLine("            Mediator.uow.save()")
            appendLine("            return Response()")
            appendLine("        }")
            appendLine("    }")
            appendLine("    class Request : RequestParam<Response>")
            appendLine("    class Response")
            appendLine("}")
        }

        return listOf(
            GenerationResult(
                fileName = fileName,
                content = content,
                packageName = context.finalPackage,
                type = OutputType.CONFIGURATION,
            )
        )
    }
}
