package com.only4.codegen.engine.generation.design

import com.only4.codegen.engine.generation.IGenerationStrategy
import com.only4.codegen.engine.output.GenerationResult
import com.only4.codegen.engine.output.OutputType

class V2DomainEventHandlerStrategy : IGenerationStrategy<HandlerV2Context> {
    override fun generate(context: HandlerV2Context): List<GenerationResult> {
        val fileName = "${context.className}.kt"
        val content = buildString {
            appendLine("package ${context.finalPackage}")
            context.imports.distinct().forEach { imp -> appendLine("import $imp") }
            appendLine()
            appendLine("/**")
            appendLine(" * ${context.description}")
            appendLine(" * Generated by V2 engine")
            appendLine(" */")
            context.annotations.forEach { ann -> appendLine(ann) }
            appendLine("class ${context.className} ${context.implements} {")
            appendLine("    ${context.methodSignature} {")
            appendLine("        ${context.methodBody}")
            appendLine("    }")
            appendLine("}")
        }
        return listOf(
            GenerationResult(
                fileName = fileName,
                content = content,
                packageName = context.finalPackage,
                type = OutputType.SERVICE,
            )
        )
    }
}
