package com.only4.codegen.engine.generation.design

import com.only4.codegen.engine.generation.IGenerationStrategy
import com.only4.codegen.engine.output.GenerationResult
import com.only4.codegen.engine.output.OutputType

class V2ValidatorStrategy : IGenerationStrategy<DesignV2Context> {
    override fun generate(context: DesignV2Context): List<GenerationResult> {
        val fileName = "${context.className}.kt"
        val content = buildString {
            appendLine("package ${context.finalPackage}")
            appendLine()
            appendLine("/**")
            appendLine(" * ${context.description}")
            appendLine(" * Generated by V2 engine")
            appendLine(" */")
            appendLine("class ${context.className} {")
            appendLine("    fun validate() : Boolean = true")
            appendLine("}")
        }
        return listOf(
            GenerationResult(
                fileName = fileName,
                content = content,
                packageName = context.finalPackage,
                type = OutputType.CONFIGURATION,
            )
        )
    }
}
